- name: Variable on Play Level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}

#Note: if we declare a varibale in PLAY level thenall the tasks can access that variables.

- name: Variables from File in Play Level
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL ={{URL}}