- name: Conditions
  hosts: localhost
  vars:
    a: 2
    b: abc2
    c: false
  tasks:
    - name: print 1
      debug:
        msg: a is equal to 1
      when: a == 1
    - name: print 2
      debug:
        msg: b is equal to abc
      when: b == "abc"
    - name: print 3
      debug:
        msg: c is true
      when: c