#Become means to run the script as root user if yes the script will run as root user



- name: Setup Frontend Component
  hosts: FRONTEND
  become: yes
  roles:
    - frontend

- name: Download Frontend from Git ropo and Extract it
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes


#- name: Setup MongoDB Component
#  hosts: MONGODB
#  roles:
#    - mongodb