- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: Download Frontend from Git ropo and Extract it
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Remove previous content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent #means doesn't want it

- name: Copy Roboshop Content
  ansible.builtin.template:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Update Roboshop cong
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.congf
  notify: restart nginx

- name: Update Nginx Config
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Start nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
