- name: Set Hostname
  ansible.builtin.shell: set-hostname {{COMPONENT}}

- name: Install Premetheus Node Exporter
  shell: curl https://raw.githubusercontent.com/linuxautomations/labautomation/master/tools/prometheus-node-exporter/install.sh | bash
  when: APPTYPE == "app" or APPTYPE == "web"
# we install only node in the applications not in the databases

- name: Install Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat
  when: APPTYPE == "app" or APPTYPE == "web"