

- name: Install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Setup App User and App Code
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Install {{COMPONENT}} packages based on packages.json
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: print
  debug:
    msg: "{{appUser}}"

- name: Replacing UID and GID {{COMPONENT}} config
  lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    search_string: "{{item.search}}"
    line: "{{item.search}} = {{item.replace}}"
  loop:
    - {search: uid, replace: "{{appUser.uid}}"}
    - {search: gid, replace: "{{appUser.group}}"}

- name: Configure SystemD for {{COMPONENT}}
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd