- name: Print
  ansible.builtin.debug:
    msg: Hello from role

- name: Print URL
  ansible.builtin.debug:
    msg: "{{URL}}"

- name: Print file
  copy:
    src: sample.txt
    dest: /tmp/sample-file.txt
  vars:
    COURSE: DEVOPS

- name: Copy a template
  template:
    src: sample.txt
    dest: /tmp/sample-temp.txt
  vars:
    COURSE: DEVOPS