groups:
- name: RoboShopAlerts
  rules:
  - alert: DiskUsageAlertWarning
    expr: ceil ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100)  > 50
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: High Disk Usage Alert Warning
  - alert: DiskUsageAlertCritical
    expr: ceil ((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_avail_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100)  > 70
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: High Disk Usage Alert Critical


  - alert: FrontendServiceAlert
    expr: node_systemd_unit_state{name=nginxe.service", state="active"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Frontend service Alert
